# -*- coding: utf-8 -*-
"""Lp2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tD1JMBViJStJ6lGkCQQmUmKV_ybhywb3
"""

!pip install botometer
!pip install tweepy==3.10.0
!pip install tweepy
!pip install requests

user="@DCComics"
import botometer

rapidapi_key = "55fce6948emshe5eda330a114078p188d04jsna260ea0dc2bc"
twitter_app_auth = {
    'consumer_key': 'kzpMI81MuaDXpVIYfbDGGN6rw',
    'consumer_secret': 'iZDWXYq6PZUa5sDOPNtv8g2tMiXActCJOzJJr99JptulkWBFFe',
    'access_token': '1568769599771971584-qBffkygf2rzveFGQ5eSLqnCgmwwJGd',
    'access_token_secret': 'SIRdNbivIoxhTbR285qBpJDkLWfbyKbl1MBLrMRtcdyry',
  }
bom = botometer.Botometer(wait_on_ratelimit=True,
                          rapidapi_key=rapidapi_key,
                          **twitter_app_auth)

# Check a single account by screen name

try:
  result = bom.check_account(user)
except Exception:
  result = "botometer was not able to assess this user! Try a new user."
print(result)

botscore = result['raw_scores']['universal']['overall']

import tweepy
from tweepy import OAuthHandler
consumer_key =  'kzpMI81MuaDXpVIYfbDGGN6rw'
consumer_secret = 'iZDWXYq6PZUa5sDOPNtv8g2tMiXActCJOzJJr99JptulkWBFFe'
access_key  = '1568769599771971584-qBffkygf2rzveFGQ5eSLqnCgmwwJGd'
access_secret = 'SIRdNbivIoxhTbR285qBpJDkLWfbyKbl1MBLrMRtcdyry'


auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)
user = "nananmjk"


try:
  u = api.get_user(user)
  userID = 1
except Exception:
  userID = -1

print(userID)